[package]
name = "url_shortener"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
redis = { version = "0.27.5", features = ["aio", "tokio-comp"] }
tokio = { version = "1.41.1", features = ["full"] }

